
development:
  adapter: postgresql
  database: match_db
  port: 5433
  username: postgres
  password: admin
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: match_db
  port: 5433
  username: postgres
  password: admin
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: match_db
  port: 5433
  username: postgres
  password: admin
  pool: 5
  timeout: 5000